<?php
/**
 * ExtSignerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eContract API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ExtSignerTest Class Doc Comment
 *
 * @category    Class
 * @description Signer personal data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtSignerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExtSigner"
     */
    public function testExtSigner()
    {
    }

    /**
     * Test attribute "signer_type_code"
     */
    public function testPropertySignerTypeCode()
    {
    }

    /**
     * Test attribute "flow_process_code"
     */
    public function testPropertyFlowProcessCode()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "surname"
     */
    public function testPropertySurname()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "sex"
     */
    public function testPropertySex()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "mail"
     */
    public function testPropertyMail()
    {
    }

    /**
     * Test attribute "citizenship"
     */
    public function testPropertyCitizenship()
    {
    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "birth_province"
     */
    public function testPropertyBirthProvince()
    {
    }

    /**
     * Test attribute "birth_city"
     */
    public function testPropertyBirthCity()
    {
    }

    /**
     * Test attribute "birth_country"
     */
    public function testPropertyBirthCountry()
    {
    }

    /**
     * Test attribute "residence_province"
     */
    public function testPropertyResidenceProvince()
    {
    }

    /**
     * Test attribute "residence_city"
     */
    public function testPropertyResidenceCity()
    {
    }

    /**
     * Test attribute "residence_address"
     */
    public function testPropertyResidenceAddress()
    {
    }

    /**
     * Test attribute "residence_address_number"
     */
    public function testPropertyResidenceAddressNumber()
    {
    }

    /**
     * Test attribute "residence_cap"
     */
    public function testPropertyResidenceCap()
    {
    }

    /**
     * Test attribute "residence_country"
     */
    public function testPropertyResidenceCountry()
    {
    }

    /**
     * Test attribute "identification_doc_type"
     */
    public function testPropertyIdentificationDocType()
    {
    }

    /**
     * Test attribute "identification_doc_number"
     */
    public function testPropertyIdentificationDocNumber()
    {
    }

    /**
     * Test attribute "identification_doc_release_authority"
     */
    public function testPropertyIdentificationDocReleaseAuthority()
    {
    }

    /**
     * Test attribute "identification_doc_country"
     */
    public function testPropertyIdentificationDocCountry()
    {
    }

    /**
     * Test attribute "identification_doc_city_release"
     */
    public function testPropertyIdentificationDocCityRelease()
    {
    }

    /**
     * Test attribute "identification_doc_province_release"
     */
    public function testPropertyIdentificationDocProvinceRelease()
    {
    }

    /**
     * Test attribute "identification_doc_release_date"
     */
    public function testPropertyIdentificationDocReleaseDate()
    {
    }

    /**
     * Test attribute "identification_doc_expiration_date"
     */
    public function testPropertyIdentificationDocExpirationDate()
    {
    }
}
